services:
  web_api:
    build:
      context: .
    container_name: nginx-api-container
    ports:
      - "8081:80"
    volumes:
      - ./html_api:/usr/share/nginx/html
      - ./nginx_api.conf:/etc/nginx/nginx.conf
    depends_on:
      - db

  web_app:
    build:
      context: .
    container_name: nginx-app-container
    ports:
      - "8082:80"
    volumes:
      - ./html_app:/usr/share/nginx/html
      - ./nginx_app.conf:/etc/nginx/nginx.conf
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: plantieguard
      MYSQL_USER: plantieguard_user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
